### ISSUE TITLE
データフェッチライブラリ導入について

### ISSUE THREAD

**Issue by shinyamamoto0422** [TechUni2020/member-site#109]
# 概要

# データフェッチ系ライブラリ
- SWR
- React Query（tanstack query）
- RTK Query（これはRedux用なのでなし？）

# 疑問
- そもそも途中から入れることに関して、ハードル高すぎないか
-

**Comment by code-yy** [comment]
自分はリファクタかねて導入ありだとと思ってます！！

> RTK Query（これはRedux用なのでなし？）

これは俺初めて聞いた。けど使うならSWRかtanstack queryになる気がしてる！

@GitHayato 
SWRか、tanstack queryのどちらが良いとかの意見はありますでしょうか？？
SWRは少し触ったことありますが、tanstack queryはほぼ初見になります。

**Comment by GitHayato** [comment]
RTK QueryはRedux Toolkitと相性のいいキャッシュライブラリですね！高機能だけど、Redux Toolkitと一緒に使うことが前提とされているので、今回はなしかなと。

Tanstack QueryはReact Queryですね！
Tanstack QueryもSWRもkeyをもとにキャッシュを持つようになっていると思うんですけど、僕の所感はTanstack Queryのほうが高機能なイメージが有りますね

Tanstack Query僕も使ったことないですけど、SWRはisLoading, isFetching, mutationがないのがいまいちなのと、DevToolsがあるから、個人的にはこれからTanstack Queryをメインで使っていこうかなと思っていたところです。

このあたり参考になるかなと
https://zenn.dev/yoshiko/scraps/ff28fabafbc847

**Comment by GitHayato** [comment]
@code-yy @shinyamamoto0422

**Comment by GitHayato** [comment]
ちゃんと調べてないけど、おそらく、RTKQueryと同じく、mutationが用意されているので、mutateしたあとに、query keyをinvalidate keyに指定することで、キャッシュを自動で更新してくれる

**Comment by shinyamamoto0422** [comment]
> SWRはisLoading, isFetching, mutationがない

これは、確かに微妙ですね。笑
なら、React Queryを導入する方向でいきましょうか！

@code-yy ゆーとくんもそれでいい？？

もし、どっちが良いのかちゃんと資料読んだ上で決めたかったら
- https://zenn.dev/terrierscript/articles/2020-07-28-swr-react-query
- https://dev.classmethod.jp/articles/react-query-or-swr/

**Comment by code-yy** [comment]
いいと思います！
けど一旦機能の方を先に実装しないと、おそらく色々不具合も出ると思うので、優先順位はあくまでもアプリの完成にするべきかなと！

**Comment by code-yy** [comment]
ガチ学びです。ありがとうございます🙇‍♂️

https://github.com/TechUni2020/member-site/issues/109#issuecomment-1237729131

**Comment by GitHayato** [comment]
@code-yy 
> ガチ学びです。ありがとうございます🙇‍♂️
いえ！頑張ってください！
