### ISSUE TITLE
「全員」のメンバーが多くなったときに、横スクロールできてしまう

### ISSUE THREAD

**Issue by shinyamamoto0422** [TechUni2020/member-site#128]
overscrollなんたらで @code-yy 実装しといて下さい

<img width="674" alt="image" src="https://user-images.githubusercontent.com/83487508/188921799-feb6733b-4283-4ceb-9a4e-611e2eb0eeda.png">

**Comment by code-yy** [comment]
@shinyamamoto0422 
これ、修正する？？
既存のままでいい？？👀

**Comment by code-yy** [comment]
なんか現状の感じの方がユーザーどれだけいるかわかりやすいし、いいかもね！

**Comment by shinyamamoto0422** [comment]
> @shinyamamoto0422 
> 
> これ、修正する？？
> 
> 既存のままでいい？？👀

あー、スクロールできるようにはしないでいいと思う！

ただ、このまま145にん登録した場合、［全員］のところが流石に多すぎるので
3列になった時点で、隠す・開くボタンを押したら145人出る感じにしようかなって思ってる！
（他も全部そうしたい）

**Comment by code-yy** [comment]
おけおけ！
それじゃ一旦このissueは閉じて、別でIssue作るわ！

**Comment by shinyamamoto0422** [comment]
> おけおけ！
> 
> それじゃ一旦このissueは閉じて、別でIssue作るわ！

ありがと！！
@code-yy
