### ISSUE TITLE
リンク踏んだ後のページを作成

### ISSUE THREAD

**Issue by shouhi** [TechUni2020/member-site#134]
# 概要
Twitterに載せることを考えると、リンク踏んだ後の挙動がログインはあまり良くないと思う。

#実装案
・LPの作成
⇨僕ならホームページの新規入会者さんはこちらの所のリンクをメンバーサイト先にする。

・最初にGitHubログイン、登録してからステップが表示されるが、最初にステップのところを表示して、
①GitHubログイン
②個人情報入力
③認証(コミッティー側で確認します)
④Slackへの参加

みたいにするとわかりやすいと思う
#理由
ユーザーがはじめにこのアプリを使うことを考えたときにいきなりサインアップを求めることはユーザーへの不安感を煽る。

#参考
しまぶーさんのオンラインサロン

**Comment by shinyamamoto0422** [comment]
これに関しては、最初からLPを作ることの工数を加味した上で
Tech.Uniにそもそも所属している学生なので、

> ユーザーへの不安感を煽る
と言うことは考慮しなくて大丈夫だと判断し無しにしました。

**Comment by shouhi** [comment]
> これに関しては、最初からLPを作ることの工数を加味した上で
> 
> Tech.Uniにそもそも所属している学生なので、
> 
> 
> 
> > ユーザーへの不安感を煽る
> 
> と言うことは考慮しなくて大丈夫だと判断し無しにしました。
> 
> 

なるほど！
たしかにSlack認証に変えるのであれば僕もこの機能要らないかなと思いました！

ただGoogle認証のままであれば実装が合理的でないのでやめて欲しいなとは思います😓
合理的でない理由
①Googleアカウントを求める理由がない
⇨個人情報の登録を求めてるためGoogleアカウントで登録する理由がよくわからなかった
②入会手順(参加した後の初期動作)が多すぎる
・Googleフォームで個人情報送信
・Slackに参加
・メンバーサイトに登録
・個人情報入力
・幹部が確認して承認されたら参加

- それであればそもそも入会する際にメンバーサイトへ飛ばして個人情報入力して幹部が承認した場合にメンバーサイトへアクセス⇨(承認した際にメールアドレス等にSlackのリンクが送るなどといった裏付けの理由があればGoogle認証はたしかにありだなと思う)

おそらく、認証箇所はFirebaseを使ってることもあり限られたプロバイダーで認証を考えられたかと思いますが、そもそもなぜその認証が必要であるかといったところは大事なのではないかなと少し思います🙇‍♂️

**Comment by shinyamamoto0422** [comment]
承知です！！
