### ISSUE TITLE
初回登録

### ISSUE THREAD

**Issue by shinyamamoto0422** [TechUni2020/member-site#20]
## 登録の流れ

- [ ] ようこそなどのwelcome文＆登録お願いします
- [ ] フォームが出てくる
- [ ] 大学・学年・学部（必須）
- [ ] 興味のある分野を選択
- [ ] Tech.Uniでは1on1を実施しています。メンターする側に回ってもらえる方を
- [ ] 自己紹介文（任意）
- [ ] twitter・instagram・github・qitta（任意）

**Comment by code-yy** [comment]
最初の登録ではidが空なので、登録後にuidを入れて登録済みかどうかを判断させる

**Comment by shinyamamoto0422** [comment]
承認の流れ
1. 初回登録で、google loginする
2. stasuが0ならば、承認されてないと判断→signupページにリダイレクト
3. signupページで
　- 名前
　- メールアドレス
　- 大学・学年・学部
　- github・twitter・instagram
　- 最も興味のある分野
　- よく使用する言語・フレームワーク・ライブラリー
　- 一言
　- 1on1を希望しますか？
4. 「承認待ち画面に遷移する」
5. Admin側ユーザーが0を1に更新する
6. useEffect時に1であること・currentUserにデータが入っていることを見てhomeにリダイレクト
