### ISSUE TITLE
管理画面作成

### ISSUE THREAD

**Issue by mine2424** [TechUni2020/member-site#22]
# 概要
- TechUniメンバーのみアクセス権限を持たせるようにユーザー管理画面を作成
#実装案
- firebase authの新規登録が来たらpenddingみたいにしてユーザー側では待ち状態となる
- そして、管理画面上に承認待ちのユーザーとして表示される
- 事前に教えてもらった登録方法とそれに対応するidを照合してあっていたら手動で管理者が承認する
- また、退会する際もその管理画面からユーザーを削除できるようにする
#理由

#参考

**Comment by code-yy** [comment]
- 一覧 (必須)
 - 承認待ちページ (承知待ちページは後でもいい)
 - イベント告知
 - 検索できるように (後でもいい)

**Comment by code-yy** [comment]
- メンバー管理 UserGroupIcon
- イベント アイコンを取ってくる https://heroicons.com/

**Comment by shinyamamoto0422** [comment]
# イベント作成ページ（通知送信）
- イベントを作成
- いつ・どこで・主催者・zoomなどのリンク
- formを作る
- user側の送信データに対して、その数を数える＋profileImageを表示、realtimeで更新する
- 通知を全員 or コミッティーメンバー or 1回生 or 2回生 or 4回生などに送信するみたいなのを選べるようにしたい

**Comment by code-yy** [comment]
firebase側で、承認かどうかを変更できるようにする

**Comment by code-yy** [comment]
これ一旦できたので、closeします。
今後追加したい機能は別Issueで既にあるので！
