### ISSUE TITLE
開発チームの技術ブログをまとめて表示できるように

### ISSUE THREAD

**Issue by code-yy** [TechUni2020/member-site#50]
# 概要
開発チームの技術ブログをまとめて表示できるように

#実装案
- Catnoseさんのこのテンプレートリポジトリを使用する
https://github.com/catnose99/team-blog-hub

- member.tsで表示するメンバーの情報を管理しているようなので、Firebaseの情報をもとにここに追加していく。

- リポジトリを使用するなら、これは別サイトとして扱って、メンバーサイトにはリンクの設置だけの方がいいかも？？

#参考

- https://zenn.dev/nkzn/articles/setup-team-blog-hub-deploy
- https://zenn.dev/catnose99/articles/cb72a73368a547756862

**Comment by shinyamamoto0422** [comment]
@code-yy 
issue整理のために、これ閉じさせてもらいます！

https://www.notion.so/shinyamamoto/9c596a7e6a534d409e234e51a3ffcafd#2866e677f95948f58e0fdb153c52cbf7
ここに移しました！！

**Comment by code-yy** [comment]
おけい！
